### PR TITLE
Fix typo in protocol.rs

### PR DESCRIPTION
**Pull request by wischi-chr**
Just found this typo while reading through the source code.

### CODE REVIEW

**Comment by sciguy16** [comment]
Good spot, thank you!

**Comment by wischi-chr** [comment]
Looks like the build failed. FYI I actually just edited the line in GitHub and haven't tested it locally. Regarding semver it's definitely a breaking change. Tomorrow I might find time to check why the build failed.

**Comment by sciguy16** [comment]
The build failure is from a failing clippy lint which I've just fixed in #4 - if you're able to rebase onto main then it should all pass now

**Comment by sciguy16** [comment]
Thank you!

**Pull request merged**
